# Path to your oh-my-zsh installation.
export ZSH=${ENV_DIR_PATH}/terminal/oh-my-zsh
source ${ENV_DIR_PATH}/terminal/antigen/antigen.zsh

antigen use oh-my-zsh

# Themes
antigen theme agnoster

# Plugins
antigen bundle git

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   antigen bundle archlinux
elif [[ "$unamestr" == 'Darwin' ]]; then
   antigen bundle brew
fi

antigen bundle tmux
antigen bundle docker
antigen bundle pip
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# Tell antigen that you're done.
antigen apply

# Configure autosuggestion color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

# Vim is my editor
export EDITOR="vim"
alias vim="nvim"

alias tmux="tmux -2"

# Override Prompt for faster prompt
function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}${ZSH_THEME_GIT_PROMPT_CLEAN}${ZSH_THEME_GIT_PROMPT_SUFFIX}"
}
alias mybranch='git branch | grep ^\* | awk "{ print \$2 }"'

# Load functions:
autoload -U zmv

#### Extra settings.

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
